### ISSUE TITLE
Support fsGroupPolicy and/or volume_mount_group

### ISSUE THREAD

**Issue by jvstein** [weka/csi-wekafs#14]
The current driver doesn't appear to support fsGroupPolicy as described on the [CSI Driver fsGroup Support](https://kubernetes-csi.github.io/docs/support-fsgroup.html) page and the [design doc](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/2317-fsgroup-on-mount/README.md).

With the default StorageClass `permissions: "0750"` value, I'm running into trouble starting pods as non-root users without getting initial permission problems on lots of files.

**Comment by sergeyberezansky** [comment]
Thank you @jvstein!
We have addressed this issue in the upcoming version that will be released in the next weeks.
Please stay tuned

**Comment by sergeyberezansky** [comment]
Implemented in release 2.0.0
