### ISSUE TITLE
Allow overriding of fsGroupPolicy in HelmChart

### ISSUE THREAD

**Issue by derselbst** [weka/csi-wekafs#249]
Hi Sergey,

as discussed, we would like to be able to override the value for `fsGroupPolicy` of the CSIDriver:

https://github.com/weka/csi-wekafs/blob/bd2e05e7d2d4d51bc6896ad51d5276393eb1913e/charts/csi-wekafsplugin/templates/driver.yaml#L15

Currently this is hardcoded to `File`. This causes a serious problem: Consider a statically provisioned volume with a few million files in it. If that volume is mounted by many users in many pods, the kubelet will chmod / chown all the files in that volume when starting pods. This can take a very long time, during which the kubelet is busy and not willing to e.g. terminate other pods.

This problem even occurs, when people do not specify `fsGroup` in their pod spec. In this case it just defaults to some value. And if that default owner / file mode doesn't match with the one in the volume (because e.g. someone as made a modification to a file or directory),  the kubelet will chmod / chmown again.

[Kubernetes suggests setting the `fsGroupChangePolicy` in each pod manifest to `OnRootMismatch`.](https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/) But this is not sufficient either, because if a mismatch is detected in the root directory, the kubelet will still do chmod / chown on everything.

Hence, the only option we see is to set the `fsGroupPolicy` of the CSIDriver to `None`, to prevent the kubelet from messing with the permissions. So having a way to specify that in the Helm chart would be nice :)

**Comment by sergeyberezansky** [comment]
Hi Tom,
First of all it was really nice to see you in person at the #ISC24

We will make sure to address this in the next release of the CSI plugin.
Please note though, the CSI driver object is immutable and it might require to uninstall and completely reinstall the plugin.

**Comment by derselbst** [comment]
I can confirm that since we have set the  `fsGroupPolicy` to `None` we observe that pods are starting instantly and no longer attempt to chown all the files in the mounted PVC. Thanks!
