### ISSUE TITLE
Per PVC statistics unavailable

### ISSUE THREAD

**Issue by davegreen** [weka/csi-wekafs#271]
I don't seem to be able to get metrics for each PVC mounted by the system from the Weka CSI driver, such as:

kubelet_volume_stats_capacity_bytes - the per-PVC capacity in bytes.
kubelet_volume_stats_used_bytes - the per-PVC space usage in bytes.
kubelet_volume_stats_available_bytes - the per-PVC free space in bytes.

Is there a specific configuration option needed to enable these, or is it not currently supported by the driver at present?

**Comment by sergeyberezansky** [comment]
Hello Dave, currently not supported.

**Comment by davegreen** [comment]
No worries, thanks for letting me know!
Thanks,
Dave Green

**Comment by sergeyberezansky** [comment]
@davegreen, the metrics will be added in version 2.5.0, stay tuned.
For reference, internal ticket: CSI-252
Those are the metrics collected:
```
kubelet_volume_stats_capacity_bytes
kubelet_volume_stats_available_bytes
kubelet_volume_stats_used_bytes
kubelet_volume_stats_inodes
kubelet_volume_stats_inodes_free
kubelet_volume_stats_inodes_used
```

**Comment by sergeyberezansky** [comment]
Closing the ticket as resolved in the upcoming version.

**Comment by sergeyberezansky** [comment]
Closing the ticket as resolved in the upcoming version.
