### ISSUE TITLE
Feature request: affinity for controller and separated nodeSelector for controller and node

### ISSUE THREAD

**Issue by jslouisyou** [weka/csi-wekafs#350]
Hello, WEKA team.

I faced an issue while deploying `csi-wekafs` plugin into Kubernetes. I found that there are 2 components - `controllerserver` and `nodeserver` in `csi-wekafs` plugin and I have multiple nodes which assigned with several roles, e.g. `cpu` and `gpu` and so on.

I wanted to deploy `controllerserver` to only `cpu` nodes but there isn't any `affinity` section only for `controllerserver` and I found `nodeSelector` term in Helm chart, but this is shared for both `controllerserver` and `nodeserver` so I couldn't use it.

https://github.com/weka/csi-wekafs/blob/52e0bf0285f2737b3d9306683f6c0d54eb03c4a8/charts/csi-wekafsplugin/templates/controllerserver-statefulset.yaml#L30

Could you please review that below requests?
1. Add `affinity` for `controllerserver`
2. Separate `nodeSelector` term for `controllerserver` and `nodeserver`

Thanks!

**Comment by sergeyberezansky** [comment]
Hello jslouisyou,
Thank you, this will be added in version 2.5.1

**Comment by jslouisyou** [comment]
Thanks @sergeyberezansky.
It would be great if above prerequisite is specifically mentioned separately in here: https://github.com/weka/csi-wekafs?tab=readme-ov-file#pre-requisite

**Comment by sergeyberezansky** [comment]
Internal issue for tracking: CSI-295
